# /// script
# requires-python = ">=3.10"
# dependencies = ["pillow>=10", "pyyaml>=6"]
# ///
"""Prepare photographs for the site.

    uv run scripts/photos.py add ~/Pictures/selected/DSC01521.jpg [...]
    uv run scripts/photos.py social DSC01521 [--focus-y 0.5]

`add` writes web-sized WebP copies to images/photos/ (all metadata, including
GPS, is dropped), records size / colour / camera settings in
_data/photo_meta.yml (generated, safe to overwrite) and appends a stub to
_data/photos.yml (hand-edited: order, titles, alt text) for new photos.

`social` crops a 1200x630 JPEG for link previews (images/og-image.jpg).
"""

from __future__ import annotations

import argparse
import sys
from fractions import Fraction
from io import BytesIO
from pathlib import Path

import yaml
from PIL import ExifTags, Image, ImageCms, ImageOps

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "images" / "photos"
META_FILE = ROOT / "_data" / "photo_meta.yml"
LIST_FILE = ROOT / "_data" / "photos.yml"

LONG_EDGES = (800, 1600, 2560)  # long-edge sizes of the WebP variants
WEBP_QUALITY = 82
CAMERA_NAMES = {"ILCE-7CM2": "Sony α7C II"}
TAG = {name: code for code, name in ExifTags.TAGS.items()}


def to_srgb(im: Image.Image) -> Image.Image:
    """Return an RGB image in sRGB, converting from an embedded ICC profile if present."""
    icc = im.info.get("icc_profile")
    if icc:
        try:
            src = ImageCms.ImageCmsProfile(BytesIO(icc))
            dst = ImageCms.createProfile("sRGB")
            return ImageCms.profileToProfile(im, src, dst, outputMode="RGB")
        except (ImageCms.PyCMSError, OSError) as err:
            print(f"  warning: ICC conversion failed ({err}); using pixels as-is", file=sys.stderr)
    return im.convert("RGB")


def shutter(value) -> str | None:
    if not value:
        return None
    seconds = float(value)
    if seconds >= 1:
        return f"{seconds:g} s"
    return f"1/{round(1 / seconds)} s"


def exif_summary(im: Image.Image) -> dict:
    exif = im.getexif()
    sub = exif.get_ifd(ExifTags.IFD.Exif)
    model = (exif.get(TAG["Model"]) or "").strip()
    make = (exif.get(TAG["Make"]) or "").strip().title()
    taken = sub.get(TAG["DateTimeOriginal"]) or exif.get(TAG["DateTime"])
    focal, aperture = sub.get(TAG["FocalLength"]), sub.get(TAG["FNumber"])
    iso = sub.get(TAG["ISOSpeedRatings"])
    summary = {
        "taken": taken[:10].replace(":", "-") if taken else None,
        "camera": CAMERA_NAMES.get(model) or " ".join(x for x in (make, model) if x) or None,
        "lens": (sub.get(TAG["LensModel"]) or "").strip() or None,
        "focal_length": f"{float(focal):g} mm" if focal else None,
        "aperture": f"f/{float(aperture):g}" if aperture else None,
        "shutter": shutter(sub.get(TAG["ExposureTime"])),
        "iso": int(iso) if iso else None,
    }
    return {k: v for k, v in summary.items() if v is not None}


def average_colour(im: Image.Image) -> str:
    r, g, b = im.resize((1, 1), Image.Resampling.BOX).getpixel((0, 0))
    return f"#{r:02x}{g:02x}{b:02x}"


def load_meta() -> dict:
    if META_FILE.exists():
        return yaml.safe_load(META_FILE.read_text()) or {}
    return {}


def listed_ids() -> set[str]:
    if not LIST_FILE.exists():
        return set()
    return {str(p["id"]) for p in yaml.safe_load(LIST_FILE.read_text()) or [] if "id" in p}


def add(paths: list[Path]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    meta, known = load_meta(), listed_ids()
    stubs = []
    for path in paths:
        if not path.is_file():
            sys.exit(f"error: {path} is not a file")
        photo_id = path.stem
        with Image.open(path) as raw:
            summary = exif_summary(raw)
            im = to_srgb(ImageOps.exif_transpose(raw))
        width, height = im.size
        variants = []
        for edge in LONG_EDGES:
            scale = min(1.0, edge / max(width, height))  # never upscale
            size = (round(width * scale), round(height * scale))
            if size[0] in variants:
                continue
            target = OUT_DIR / f"{photo_id}-{size[0]}.webp"
            im.resize(size, Image.Resampling.LANCZOS).save(target, "WEBP", quality=WEBP_QUALITY, method=6)
            variants.append(size[0])
        meta[photo_id] = {
            "width": width,
            "height": height,
            "widths": variants,
            "color": average_colour(im),
            **summary,
        }
        print(f"{photo_id}: {width}x{height} -> {variants} ({meta[photo_id]['color']})")
        if photo_id not in known:
            stubs.append(photo_id)
            known.add(photo_id)
    META_FILE.write_text(
        "# Generated by scripts/photos.py - edit _data/photos.yml instead.\n"
        + yaml.safe_dump(dict(sorted(meta.items())), sort_keys=False, allow_unicode=True)
    )
    if stubs:
        with LIST_FILE.open("a") as fh:
            for photo_id in stubs:
                fh.write(f"\n- id: {photo_id}\n  title: \"\"\n  place: \"\"\n  alt: \"\"\n")
        print(f"Appended {len(stubs)} stub(s) to {LIST_FILE.relative_to(ROOT)}: fill in title/place/alt.")


def social(photo_id: str, focus_y: float) -> None:
    sources = sorted(OUT_DIR.glob(f"{photo_id}-*.webp"), key=lambda p: int(p.stem.rsplit("-", 1)[1]))
    if not sources:
        sys.exit(f"error: no processed variants for {photo_id}; run `add` first")
    with Image.open(sources[-1]) as im:
        im = im.convert("RGB")
        ratio = Fraction(1200, 630)
        w, h = im.size
        crop_h = min(h, round(w / ratio))
        crop_w = round(crop_h * ratio)
        left = (w - crop_w) // 2
        top = round((h - crop_h) * min(max(focus_y, 0.0), 1.0))
        card = im.crop((left, top, left + crop_w, top + crop_h)).resize((1200, 630), Image.Resampling.LANCZOS)
        target = ROOT / "images" / "og-image.jpg"
        card.save(target, "JPEG", quality=85, optimize=True, progressive=True)
        print(f"wrote {target.relative_to(ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_add = sub.add_parser("add", help="process source photos")
    p_add.add_argument("paths", nargs="+", type=lambda s: Path(s).expanduser())
    p_social = sub.add_parser("social", help="make the 1200x630 link-preview image")
    p_social.add_argument("photo_id")
    p_social.add_argument("--focus-y", type=float, default=0.5, help="0 = top of photo, 1 = bottom")
    args = parser.parse_args()
    if args.cmd == "add":
        add(args.paths)
    else:
        social(args.photo_id, args.focus_y)


if __name__ == "__main__":
    main()
